FROM node:20.10.0-alpine

WORKDIR /usr/src/site.com/frontend
ADD ./dist /usr/src/site.com/frontend/dist
ADD ./entrypoint.sh /entrypoint.sh
RUN apk add gettext


ENTRYPOINT ["/bin/sh","/entrypoint.sh"]

